# Generated by Django 5.1.3 on 2024-12-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_programer_programmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='Cellphone',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
