# Generated by Django 5.1.3 on 2024-12-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_programmer_cellphone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=1)),
                ('numero_ficha', models.PositiveSmallIntegerField(max_length=7)),
                ('formacion', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
    ]
